## code to prepare `INFCspecies` dataset goes here
INFCspecies <- tibble::tribble(
  ~EPPOcode, ~pag,                    ~PrefName,
  #                     ordered by PrefName
  "ABIAL",  33L,                 "Abies alba",
  "ACRCA", 231L,             "Acer campestre",
  "ACRMS", 231L,        "Acer monspessulanum",
  "ACROP", 231L,                "Acer opalus",
  "ACRPP", 231L,        "Acer pseudoplatanus",
  "ALUCO", 245L,              "Alnus cordata",
  "ALUGL", 245L,            "Alnus glutinosa",
  "CIPBE", 259L,           "Carpinus betulus",
  "CSNSA", 273L,            "Castanea sativa",
  "CVBAR",  47L,        "Cupressus arizonica",
  "CVBSE",  47L,     "Cupressus sempervirens",
  "1EUCG", 287L,                 "Eucalyptus",
  "FAUSY", 301L,            "Fagus sylvatica",
  "FRXAN", 315L,      "Fraxinus angustifolia",
  "FRXEX", 315L,         "Fraxinus excelsior",
  "FRXOR", 315L,             "Fraxinus ornus",
  "LABAL", 399L,           "Laburnum alpinum",
  "LAXDE",  61L,              "Larix decidua",
  "OSTCA", 259L,        "Ostrya carpinifolia",
  "PIEAB",  75L,                "Picea abies",
  "PIUCE",  89L,               "Pinus cembra",
  "PIUHA", 103L,           "Pinus halepensis",
  "PIUNI", 131L,                "Pinus nigra",
  "PIUNL", 117L, "Pinus nigra subsp. laricio",
  "PIUPL", 145L,             "Pinus pinaster",
  "PIUPN", 159L,                "Pinus pinea",
  "PIURA", 187L,              "Pinus radiata",
  "PIUST", 187L,              "Pinus strobus",
  "PIUSI", 173L,           "Pinus sylvestris",
  "POPNI", 399L,              "Populus nigra",
  "POPTR", 399L,            "Populus tremula",
  "POPCN", 399L,        "Populus x canescens",
  "PRNAV", 399L,               "Prunus avium",
  "PSTME", 201L,      "Pseudotsuga menziesii",
  "QUECE", 329L,             "Quercus cerris",
  "QUEIL", 343L,               "Quercus ilex",
  "QUEPU", 357L,          "Quercus pubescens",
  "ROBPS", 371L,       "Robinia pseudoacacia",
  "SAXAL", 385L,                 "Salix alba",
  "SAXCP", 385L,               "Salix caprea",
  "SOUAI", 399L,                "Sorbus aria",
  "TILCO", 399L,              "Tilia cordata",
  "TILPL", 399L,         "Tilia platyphyllos",
  "ULMMI", 399L,                "Ulmus minor"
)
#usethis::use_data(INFCspecies, overwrite = FALSE, internal = TRUE)
